version: "3.8"

networks:
  app:
    driver: "bridge"
    enable_ipv6: true
    driver_opts:
      com.docker.network.driver.mtu: 1450

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMETHEUS_PORT}:9090"
    networks:
      - app

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: ${NAME}_nginx-exporter
    ports:
      - "9113:9113"
    command:
      - -nginx.scrape-uri=http://${NAME}_nginx/stub_status
    networks:
      - app
    depends_on:
      - nginx

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./docker/monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./docker/monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - app
    depends_on:
      - prometheus

  nginx:
    container_name: ${NAME}_nginx
    hostname: ${NAME}_nginx
    restart: always
    ports:
      - "${HTTP_PORT}:80"
      - "${SSL_PORT}:443"
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./sources:/var/www/sources
      - ./app/ssl:/var/www/ssl:ro
    networks:
      - app

  mongodb:
    container_name: ${NAME}_mongodb
    hostname: ${NAME}_mongodb
    ports:
      - "${MONGO_PORT}:27017"
    build:
      context: ./docker/mongodb
      dockerfile: Dockerfile
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - logging:${MONGO_DATA}
    networks:
      - app

  mysql:
    container_name: ${NAME}_mysql
    hostname: ${NAME}_mysql
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./:/docker-entrypoint-initdb.d
    networks:
      - app

  memcached:
    container_name: ${NAME}_memcached
    hostname: ${NAME}_memcached
    restart: always
    ports:
      - "${MEMCACHED_PORT}:11211"
    build:
      context: ./docker/memcached
      dockerfile: Dockerfile
    volumes:
      - cachedata:${MEMCACHED_CACHEDATA}
    depends_on:
      - nginx
      - mongodb
      - mysql
    networks:
      - app

  rabbitmq:
    container_name: ${NAME}_rabbitmq
    hostname: ${NAME}_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST}
    build:
      context: ./docker/rabbitmq
      dockerfile: Dockerfile
    ports:
      - "${RABBITMQ_PORT_CLIENT}:5672"
      - "${RABBITMQ_PORT}:15672"
    volumes:
      - ./${DOCKER_PATH}/${RABBITMQ_CONFIG_PATH}:/etc/rabbitmq/rabbitmq.conf:ro
    networks:
      - app

  php-fpm:
    container_name: ${NAME}_php-fpm
    hostname: ${NAME}_php-fpm
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
      args:
        - LOCALE=${LOCALE_DEFAULT}
        - TIMEZONE=${TIMEZONE_DEFAULT}
        - PUID=${PUID}
        - PGID=${PGID}
    env_file:
      - ./docker/php-fpm/conf/xdebug.env
    volumes:
      - ./${APP_LOCAL_PATH}:${APP_CONTAINER_PATH}
      - ./${DOCKER_PATH}/php-fpm/conf/php.ini:${PHP_FPM_CONFIG_PATH}:ro
    depends_on:
      - nginx
      - mongodb
      - mysql
      - rabbitmq
    networks:
      - app

volumes:
  database:
  logging:
  mysql_data:
  cachedata:
  grafana-storage:
