import { ContainedCheckboxCustomElement } from "./containedCheckbox";
import { OptionCustomElement } from "./customOption";
import { OptionListCustomElement } from "./optionList";
import { FancyDropdownCustomElement } from "./fancyDropdown";
import { ButtonsGridCustomElement } from "./buttonsGrid";
import { PhoneInputCustomElement } from "./phoneInput";
import { TextInputCustomElement } from "./textInput";
import { SearchBarCustomElement } from "./searchBar";
import { DatePickerCustomElement } from "./datePicker";
import { UserMenu } from "./userMenu";
import { BuildingCard } from "./buildingCard";
import { ImageGallery } from "./imageGallery";
import { ShareButtonCustomElement } from "./shareButton";
import { LikeButton } from "./likeButton";
import { AgentBuildingCard } from "./agentBuildingCard";
import { CatalogueFilters } from "./catalogueFilters";
import { WideBuildingCard } from "./wideBuildingCard";
import { CitySelection } from "./citySelection";

window.customElements.define('contained-checkbox', ContainedCheckboxCustomElement);
window.customElements.define('custom-select', FancyDropdownCustomElement);
window.customElements.define('option-list', OptionListCustomElement, { extends: "ul" });
window.customElements.define('custom-option', OptionCustomElement, { extends: "li" });
window.customElements.define('buttons-grid', ButtonsGridCustomElement);
window.customElements.define('phone-input', PhoneInputCustomElement);
window.customElements.define('text-input', TextInputCustomElement);
window.customElements.define('search-bar', SearchBarCustomElement);
window.customElements.define('date-picker', DatePickerCustomElement);
window.customElements.define('user-menu', UserMenu);
window.customElements.define('building-card', BuildingCard);
window.customElements.define('image-gallery', ImageGallery);
window.customElements.define('share-button', ShareButtonCustomElement);
window.customElements.define('like-button', LikeButton);
window.customElements.define('agent-building-card', AgentBuildingCard);
window.customElements.define('catalogue-filters', CatalogueFilters);
window.customElements.define('wide-building-card', WideBuildingCard);
window.customElements.define('city-selection', CitySelection);